export const BALANCE_SHEET = 'balanceSheet'
export const PROFIT_LOSS = 'profitLoss'
export const LEDGER = 'ledger'
export const GENERAL_LEDGER = 'generalLedger'
export const TRIAL_BALANCE = 'trialBalance'
export const SALES_SUMMARY = 'salesSummary'
export const SALES_PRODUCT = 'salesProduct'

export const PURCHASE_SUMMARY = 'purchaseSummary'
export const VENDOR_BALANCE = 'vendorBalance'
export const PURCHASE_SUPPLIER = 'purchaseSupplier'
export const AGED_PAYABLE = 'agedPayable'
export const PURCHASE_PRODUCT = 'purchaseProduct'

export const BANK_RECON_SUMMARY = 'bankReconSummary'
export const BANK_STATEMENT = 'bankStatement'
