import { rest, api, apiHeader } from '../config.rest'

it('Should render Config Rest', () =>
  expect(rest).toEqual({
    apiUser: '/users/:id',
    apiUsers: '/users',
    apiUserLogin: '/users/login',
    apiUserLogout: '/users/logout',
    apiUserRole: '/users/:id/roles/:role',
    apiUserRoles: '/users/:id/roles',
    apiUserStore: '/users/:id/stores',
    apiUserTotp: '/users/:id/totp',
    apiUserTotpr: '/users/:id/totp/:mode',
    apiStores: '/stores',
    apiListStores: '/list/stores',
    apiTime: '/time',
    apiMemberBirthday: '/members/bday',
    apiMobile: '/mobile',
    apiTools: '/tools',
    apiPromo: '/promo',
    apiLog: '/log',
    apiCashierUsers: '/cashiers/users',
    apiCashRegister: '/cashiers/cashregisters',
    apiVariant: '/stock/variant',
    apiSpecification: '/stock/specification',
    apiVariantStock: '/stock/variantstock',
    apiSpecificationStock: '/stock/specificationstock',
    apiSpecificationInsertStock: '/stock/specificationinsstock',
    apiFollowUp: '/followup',
    apiSequence: '/sequences',
    apiLoyalty: '/loyalty',
    apiReportCashback: '/report/cashback',
    apiReportMarketing: '/report/marketing',
    apiSocial: '/social',
    apiMemberSocial: '/membersocial',
    apiCms: '/cms',
    apiUpload: '/upload'
  })
)

it('Should render Config Api', () =>
  expect(api).toEqual({
    getIpAddress: '/utils/ipaddr',
    userInfo: '/userInfo',
    sequence: '/sequence',
    employees: '/employees',
    jobposition: '/employees/positions',
    customers: '/members',
    assets: '/assets',
    customergroup: '/members/groups',
    customertype: '/members/types',
    suppliers: '/suppliers',
    fingerprint: '/fingerprint',
    fingerprintVerification: '/fingerprint-verification',
    balance: '/balance',
    balanceDetail: '/balance-detail',
    bank: '/bank',
    city: '/cities',
    services: '/services',
    servicestype: '/misc/code/service',
    misc: '/misc',
    ipaddr: '/utils/ipaddr',
    dashboard: '/dashboard',
    dashboards: '/dashboards',
    deliveryOrder: '/delivery-order',
    menus: '/menus',
    position: '/position',
    userrole: '/misc/code/USERROLE',
    sellprice: '/misc/code/SELLPRICE',
    importstock: '/stocks/import',
    importbcarecon: '/accounting/bca-recon-import',
    brand: '/stocks/brands',
    bookmarkGroup: '/stock/bookmark-group',
    bookmark: '/stock/bookmark',
    stockcategory: '/stocks/categories',
    stock: '/stocks',
    pos: '/pos',
    posdetail: '/posdetail',
    posreport: '/posreport',
    cashEntryReport: '/report/cashentry',
    posReport: '/report/pos',
    purchasereport: '/report/purchase',
    requestCancelPos: '/request-cancel-pos',
    inventoryreport: '/report/transfer',
    adjustreport: '/report/adjust',
    fiforeport: '/report/fifo',
    servicereport: '/report/service',
    bundlingReport: '/report/bundling/daily',
    woReport: '/report/wo',
    purchase: '/purchase',
    purchaseDetail: '/purchasedetail',
    adjust: '/adjust',
    adjustDetail: '/adjustdetail',
    transfer: '/transfer',
    member: '/member',
    service: '/service',
    cashierList: '/misc/code/KASSA?fields=miscName,miscDesc&as=cashierNo,cashierDesc',
    transTypeList: '/misc/code/TRANSTYPE?fields=miscName,miscDesc,miscVariable&as=code,type,variable',
    cashierTrans: '/cashierTrans',
    cashier: '/cashiers',
    period: '/period',
    creditCharge: '/creditCharge',
    setting: '/setting',
    permission: '/permission',
    permissionrole: '/permissionrole',
    planogram: '/planogram',
    role: '/role',
    mobileBooking: '/mobile/booking',
    paymentOpts: '/payment',
    paymentValidationImport: '/payment-validation-import',
    paymentValidationImportBank: '/payment-validation-import-bank',
    paymentValidationConflict: '/payment-validation-conflict',
    paymentMachine: '/payment-machine',
    paymentMachineStore: '/payment-machine-store',
    paymentCost: '/payment-cost',
    workOrder: '/wo',
    maintenance: '/maintenance',
    marketing: '/marketing',
    paymentTransaction: '/payment-transaction',
    paylabs: '/paylabs',
    paymentXenditBalanceImport: '/payment-xendit-balance-import',
    paymentXenditBalanceImportDetail: '/payment-xendit-balance-import-detail',
    paymentXenditTransactionImport: '/payment-xendit-transaction-import',
    paymentXenditTransactionImportDetail: '/payment-xendit-transaction-import-detail',
    errorLog: '/error-log'
  })
)

it('Should render api header', () =>
  expect(apiHeader).toEqual({ Accept: 'application/json', 'Content-Type': 'application/json' })
)
