const APIV1 = '/api/v1'
const APIHOST = '192.168.88.191' // '192.168.80.64'
const APIPORT = 6401
const APIURL = `http://${APIHOST}:${APIPORT}`

module.exports = {
  CORS: `${APIURL}`,
  apiHost: `${APIHOST}`,
  authBy: 'id',
  apiPrefix: `${APIV1}`,
  apiHeader: { Accept: 'application/json', 'Content-Type': 'application/json' },
  rest: {
    apiUser: '/users/:id',
    apiUsers: '/users',
    apiUserLogin: '/users/login',
    apiUserLogout: '/users/logout',
    apiUserRole: '/users/:id/roles/:role',
    apiUserRoles: '/users/:id/roles',
    apiUserStore: '/users/:id/stores',
    apiUserTotp: '/users/:id/totp',
    apiUserTotpr: '/users/:id/totp/:mode',
    apiStores: '/stores',
    apiListStores: '/list/stores',
    apiTime: '/time',
    apiMemberBirthday: '/members/bday',
    apiMobile: '/mobile',
    apiTools: '/tools',
    apiPromo: '/promo',
    apiLog: '/log',
    apiCashierUsers: '/cashiers/users',
    apiCashRegister: '/cashiers/cashregisters',
    apiVariant: '/stock/variant',
    apiSpecification: '/stock/specification',
    apiVariantStock: '/stock/variantstock',
    apiSpecificationStock: '/stock/specificationstock',
    apiSpecificationInsertStock: '/stock/specificationinsstock',
    apiFollowUp: '/followup',
    apiSequence: '/sequences',
    apiLoyalty: '/loyalty',
    apiReportCashback: '/report/cashback'
  },
  api: {
    getIpAddress: '/utils/ipaddr',
    userInfo: '/userInfo',
    sequence: '/sequence',
    employees: '/employees',
    jobposition: '/employees/positions',
    customers: '/members',
    assets: '/assets',
    customergroup: '/members/groups',
    customertype: '/members/types',
    suppliers: '/suppliers',
    bank: '/bank',
    city: '/cities',
    services: '/services',
    servicestype: '/misc/code/service',
    misc: '/misc',
    ipaddr: '/utils/ipaddr',
    dashboard: '/dashboard',
    dashboards: '/dashboards',
    menus: '/menus',
    position: '/position',
    userrole: '/misc/code/USERROLE',
    sellprice: '/misc/code/SELLPRICE',
    brand: '/stocks/brands',
    stockcategory: '/stocks/categories',
    stock: '/stocks',
    pos: '/pos',
    posdetail: '/posdetail',
    posreport: '/posreport',
    cashEntryReport: '/report/cashentry',
    posReport: '/report/pos',
    purchasereport: '/report/purchase',
    inventoryreport: '/report/transfer',
    adjustreport: '/report/adjust',
    fiforeport: '/report/fifo',
    servicereport: '/report/service',
    bundlingReport: '/report/bundling/daily',
    woReport: '/report/wo',
    purchase: '/purchase',
    purchaseDetail: '/purchasedetail',
    adjust: '/adjust',
    adjustDetail: '/adjustdetail',
    transfer: '/transfer',
    member: '/member',
    service: '/service',
    cashierList: '/misc/code/KASSA?fields=miscName,miscDesc&as=cashierNo,cashierDesc',
    transTypeList: '/misc/code/TRANSTYPE?fields=miscName,miscDesc,miscVariable&as=code,type,variable',
    cashierTrans: '/cashierTrans',
    cashier: '/cashiers',
    period: '/period',
    creditCharge: '/creditCharge',
    setting: '/setting',
    permission: '/permission',
    permissionrole: '/permissionrole',
    role: '/role',
    mobileBooking: '/mobile/booking',
    paymentOpts: '/payment',
    workOrder: '/wo',
    maintenance: '/maintenance'
  }
}
