const APIV1 = '/api/v1'
const APIHOST = 'localhost' // '192.168.80.64'
const APIPORT = 5557
const APIURL = `http://${APIHOST}:${APIPORT}`

module.exports = {
  name: 'DMI-PoS',
  version: '2018.02.001',
  prefix: 'dmiPos',
  footerText: 'Darkotech Mandiri Indonesia',
  footerSubText: 'Point of Sales © 2017-2018',
  logo: '/logo.png',
  CORS: `${APIURL}`,
  apiHost: `${APIHOST}`,
  openPages: ['/login'],
  authBy: 'id',
  apiPrefix: `${APIV1}`,
  apiHeader: { Accept: 'application/json', 'Content-Type': 'application/json' },
  disableMultiSelect: true,
  rest: {
    apiUser: `${APIURL}${APIV1}/users/:id`,
    apiUsers: `${APIURL}${APIV1}/users`,
    apiUserLogin: `${APIURL}${APIV1}/users/login`,
    apiUserLogout: `${APIURL}${APIV1}/users/logout`,
    apiUserRole: `${APIURL}${APIV1}/users/:id/roles/:role`,
    apiUserRoles: `${APIURL}${APIV1}/users/:id/roles`,
    apiUserStore: `${APIURL}${APIV1}/users/:id/stores`,
    apiUserTotp: `${APIURL}${APIV1}/users/:id/totp`,
    apiUserTotpr: `${APIURL}${APIV1}/users/:id/totp/:mode`,
    apiStores: `${APIURL}${APIV1}/stores`,
    apiTime: `${APIURL}${APIV1}/time`,
    apicustomerbirthday: `${APIURL}${APIV1}/members/bday`
  },
  api: {
    getIpAddress: `${APIURL}${APIV1}/utils/ipaddr`,
    userInfo: `${APIV1}/userInfo`,
    sequence: `${APIURL}${APIV1}/sequence`,
    employees: `${APIURL}${APIV1}/employees`,
    jobposition: `${APIURL}${APIV1}/employees/positions`,
    customers: `${APIURL}${APIV1}/members`,
    customergroup: `${APIURL}${APIV1}/members/groups`,
    customertype: `${APIURL}${APIV1}/members/types`,
    suppliers: `${APIURL}${APIV1}/suppliers`,
    city: `${APIURL}${APIV1}/cities`,
    services: `${APIURL}${APIV1}/services`,
    servicestype: `${APIURL}${APIV1}/misc/code/service`,
    misc: `${APIURL}${APIV1}/misc`,
    ipaddr: `${APIURL}${APIV1}/utils/ipaddr`,
    posts: `${APIV1}/posts`, // mock js ===========
    dashboard: `${APIV1}/dashboard`, // mock js ===========
    // menus: `${APIV1}/menus`,
    menus: `${APIURL}${APIV1}/menus`,
    position: `${APIURL}${APIV1}/position`, // mock js ===========
    sellprice: `${APIURL}${APIV1}/misc/code/SELLPRICE`,
    brand: `${APIURL}${APIV1}/stocks/brands`,
    stockcategory: `${APIURL}${APIV1}/stocks/categories`,
    stock: `${APIURL}${APIV1}/stocks`,
    pos: `${APIURL}${APIV1}/pos`,
    posdetail: `${APIURL}${APIV1}/posdetail`,
    posreport: `${APIURL}${APIV1}/posreport`,
    posReport: `${APIURL}${APIV1}/report/pos`,
    purchasereport: `${APIURL}${APIV1}/report/purchase`,
    adjustreport: `${APIURL}${APIV1}/report/adjust`,
    fiforeport: `${APIURL}${APIV1}/report/fifo`,
    servicereport: `${APIURL}${APIV1}/report/service`,
    purchase: `${APIURL}${APIV1}/purchase`,
    purchaseDetail: `${APIURL}${APIV1}/purchasedetail`,
    adjust: `${APIURL}${APIV1}/adjust`,
    adjustDetail: `${APIURL}${APIV1}/adjustdetail`,
    transfer: `${APIURL}${APIV1}/transfer`,
    member: `${APIURL}${APIV1}/member`,
    service: `${APIURL}${APIV1}/service`,
    cashierList: `${APIURL}${APIV1}/misc/code/KASSA?fields=miscName,miscDesc&as=cashierNo,cashierDesc`,
    transTypeList: `${APIURL}${APIV1}/misc/code/TRANSTYPE?fields=miscName,miscDesc,miscVariable&as=code,type,variable`,
    cashierTrans: `${APIURL}${APIV1}/cashierTrans`,
    period: `${APIURL}${APIV1}/period`,
    creditCharge: `${APIURL}${APIV1}/creditCharge`,
    setting: `${APIURL}${APIV1}/setting`,
    mobileBooking: `${APIURL}${APIV1}/mobile/booking`,
    paymentOpts: `${APIURL}${APIV1}/payment`
  }
}
