const APIV1 = '/api/v1'
const APIV2 = '/api/v2'
const APIHOST = '192.168.88.191'
const APIPORT = 5557
const APIURL = `http://${APIHOST}:${APIPORT}`

module.exports = {
  name: 'DMI-PoS',
  version: '2018.01.001',
  prefix: 'dmiPos',
  footerText: 'Pos © 2017-2018 Darkotech Mandiri Indonesia',
  logo: '/logo.png',
  CORS: `${APIURL}`,
  apiHost: `${APIHOST}`,
  openPages: ['/login'],
  authBy: 'id',
  apiPrefix: `${APIV1}`,
  apiHeader: { Accept: 'application/json', 'Content-Type': 'application/json' },
  disableMultiSelect: true,
  api: {
    getIpAddress: `${APIURL}${APIV1}/utils/ipaddr`,
    userPreLogin: `${APIURL}${APIV1}/users/prelogin`,
    userRole: `${APIURL}${APIV1}/users/:id/roles`,
    userTotp: `${APIURL}${APIV1}/users/:id/totp`,
    userTotpr: `${APIURL}${APIV1}/users/:id/totp/:mode`,
    userStore: `${APIURL}${APIV1}/users/:id/stores`,
    userLogin: `${APIURL}${APIV1}/users/login`,
    userLogout: `${APIURL}${APIV1}/users/logout`, // services/app.js post
    userInfo: `${APIV1}/userInfo`,
    users: `${APIURL}${APIV1}/users`,
    sequence: `${APIURL}${APIV1}/sequence`,
    user: `${APIURL}${APIV1}/users/:id`,
    employees: `${APIURL}${APIV1}/employees`,
    jobposition: `${APIURL}${APIV1}/employees/positions`,
    customers: `${APIURL}${APIV1}/members`,
    customergroup: `${APIURL}${APIV1}/members/groups`,
    customertype: `${APIURL}${APIV1}/members/types`,
    suppliers: `${APIURL}${APIV1}/suppliers`,
    city: `${APIURL}${APIV1}/cities`,
    services: `${APIURL}${APIV1}/services`,
    servicestype: `${APIURL}${APIV1}/misc/code/service`,
    misc: `${APIURL}${APIV1}/misc`,
    ipaddr: `${APIURL}${APIV1}/utils/ipaddr`,
    posts: `${APIV1}/posts`,// mock js ===========
    dashboard: `${APIV1}/dashboard`,// mock js ===========
    // menus: `${APIV1}/menus`,
    menus: `${APIURL}${APIV1}/menus`,
    position: `${APIV1}/position`,// mock js ===========
    sellprice: `${APIURL}${APIV1}/misc/code/SELLPRICE`,
    brand: `${APIURL}${APIV1}/stocks/brands`,
    stockcategory: `${APIURL}${APIV1}/stocks/categories`,
    stock: `${APIURL}${APIV1}/stocks`,
    pos: `${APIURL}${APIV1}/pos`,
    posdetail: `${APIURL}${APIV1}/posdetail`,
    posreport: `${APIURL}${APIV1}/posreport`,
    posReport: `${APIURL}${APIV1}/report/pos`,
    purchasereport: `${APIURL}${APIV1}/report/purchase`,
    adjustreport: `${APIURL}${APIV1}/report/adjust`,
    fiforeport: `${APIURL}${APIV1}/report/fifo`,
    servicereport: `${APIURL}${APIV1}/report/service`,
    purchase: `${APIURL}${APIV1}/purchase`,
    purchaseDetail: `${APIURL}${APIV1}/purchasedetail`,
    adjust: `${APIURL}${APIV1}/adjust`,
    adjustDetail: `${APIURL}${APIV1}/adjustdetail`,
    transfer: `${APIURL}${APIV1}/transfer`,
    member: `${APIURL}${APIV1}/member`,
    service: `${APIURL}${APIV1}/service`,
    cashierList: `${APIURL}${APIV1}/misc/code/KASSA?fields=miscName,miscDesc&as=cashierNo,cashierDesc`,
    transTypeList: `${APIURL}${APIV1}/misc/code/TRANSTYPE?fields=miscName,miscDesc,miscVariable&as=code,type,variable`,
    cashierTrans: `${APIURL}${APIV1}/cashierTrans`,
    period: `${APIURL}${APIV1}/period`,
    creditCharge: `${APIURL}${APIV1}/creditCharge`,
    setting: `${APIURL}${APIV1}/setting`,
    stores: `${APIURL}${APIV1}/stores`,
    mobileBooking: `${APIURL}${APIV1}/mobile/booking`,
  },
}
