const APIV1 = '/api/v1'
const APIHOST = 'localhost' // '192.168.80.64'
const APIPORT = 6401
const APIURL = `http://${APIHOST}:${APIPORT}`

module.exports = {
  CORS: `${APIURL}`,
  apiHost: `${APIHOST}`,
  authBy: 'id',
  apiPrefix: `${APIV1}`,
  apiHeader: { Accept: 'application/json', 'Content-Type': 'application/json' },
  rest: {
    apiUser: '/users/:id',
    apiUsers: '/users',
    apiUserLogin: '/users/login',
    apiUserLogout: '/users/logout',
    apiUserRole: '/users/:id/roles/:role',
    apiUserRoles: '/users/:id/roles',
    apiUserStore: '/users/:id/stores',
    apiUserTotp: '/users/:id/totp',
    apiUserTotpr: '/users/:id/totp/:mode',
    apiStores: '/stores',
    apiTime: '/time',
    apiMemberBirthday: '/members/bday'
  },
  api: {
    getIpAddress: '/utils/ipaddr',
    userInfo: '/userInfo',
    sequence: '/sequence',
    employees: '/employees',
    jobposition: '/employees/positions',
    customers: '/members',
    customergroup: '/members/groups',
    customertype: '/members/types',
    suppliers: '/suppliers',
    city: '/cities',
    services: '/services',
    servicestype: '/misc/code/service',
    misc: '/misc',
    ipaddr: '/utils/ipaddr',
    dashboard: '/dashboard',
    menus: `/menus`,
    position: '/position',
    sellprice: '/misc/code/SELLPRICE',
    brand: '/stocks/brands',
    stockcategory: '/stocks/categories',
    stock: '/stocks',
    pos: '/pos',
    posdetail: 'posdetail',
    posreport: '/posreport',
    posReport: '/report/pos',
    purchasereport: '/report/purchase',
    inventoryreport: '/report/transfer',
    adjustreport: '/report/adjust',
    fiforeport: '/report/fifo',
    servicereport: '/report/service',
    purchase: '/purchase',
    purchaseDetail: '/purchasedetail',
    adjust: '/adjust',
    adjustDetail: '/adjustdetail',
    transfer: '/transfer',
    member: '/member',
    service: '/service',
    cashierList: '/misc/code/KASSA?fields=miscName,miscDesc&as=cashierNo,cashierDesc',
    transTypeList: '/misc/code/TRANSTYPE?fields=miscName,miscDesc,miscVariable&as=code,type,variable',
    cashierTrans: '/cashierTrans',
    period: '/period',
    creditCharge: '/creditCharge',
    setting: '/setting',
    mobileBooking: '/mobile/booking',
    paymentOpts: '/payment'
  }
}
